security:
    providers:
      firebase_provider:
          entity:
            class: App\Entity\User
            property: firebaseUid

    firewalls:
        main:
            anonymous: true
            lazy: true
            provider: firebase_provider
            logout: 
                path: /signout

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
